# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

# Fabric Properties
# check these on https://fabricmc.net/use
minecraft_version=1.21.5
minecraft_required = >=1.21.5 <=1.21.11
minecraft_supported_versions=1.21.5,1.21.6,1.21.7,1.21.8,1.21.9,1.21.10,1.21.11
yarn_mappings=1.21.5+build.1
loader_version=0.16.14

#Fabric api
fabric_version=0.128.0+1.21.5

# Mod Properties
mod_version=1.21.11
maven_group=fzzyhmstrs
archives_base_name=structurized_reborn